
services:
  linkv-service:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - linkv-db
    restart: unless-stopped

  linkv-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: