services:
  linkv-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_linkvault
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - linkv-db


volumes:
  db_data: